---
pool:
   name: 'Azure-pipeline'
   vmImage: 'ubuntu-latest'
  
trigger:
  - main   
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.04'
      displayName:'install and build' 

- script: |
    npm install
  display name: 'npm install'  
      