---
pool: 
  name: 'Azure pipeline'
  vmImage: ubuntu-20.04
trigger:
- main    
jobs:
- job: devops1
   steps:
   - script: 'echo devops'
   - script: 'echo devops'
   - script: 'echo devops'
   - script: 'echo devops'
   - script: 'echo devops'
jobs:
- job: Azure2
   steps:
   - script: 'echo Azure'
   - script: 'echo Azure'
   - script: 'echo Azure'
   - script: 'echo Azure'
   - script: 'echo Azure'

  


  