# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

---
pool:
  name: 'default'
  vmImage: 'ubuntu-latest'
trigger:
- main

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'path'
    jdkDirectory:  /usr/lib/jvm/java-17-openjdk-amd64
    goals: 'package'
    mavenVersionOption: 'path'
    mavenDirectory: /usr/share/maven
