---
- name: tomcat on ubuntu 
  hosts: localhosts
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk--jdk
        update_cache: yes
        state: present
    - name: create a tomcat group
      ansible.builtin.gro:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
        
