---
- hosts: all
  become: true
  tasks:
  - name: Install PHP
    apt:
      name: php
      state: present
  - name: Install PHP extensions
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - php-cli
    - php-common
    - php-curl
    - php-gd
    - php-intl
    - php-json
    - php-mbstring
    - php-mysql
    - php-xml
    - php-zip
